### ISSUE TITLE
Error code 218 (Corrected typo) - Ofsted Unique reference number (URN) is required.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#122]
#### Error code
218 (Corrected typo)
#### Description to display
Ofsted Unique reference number (URN) is required.
#### DfE Long-form description of error
Please ensure Ofsted URN is recorded for ongoing placements at 1 April of the current collection year and also for new episodes from 1 April of the current collection year where the reason for new episode is P, T, B, U or S.  Ofsted URN should not be provided for the placement types listed in rule 222, for confidential placements, placements outside of England.
#### DfE suggested coding
Where `<PL>` not in 'H5'; 'P1'; 'P2'; 'P3'; 'R1'; 'R2'; 'R5'; 'T0'; 'T1'; 'T2'; 'T3'; 'T4' 'Z1' And `<PL_LA>` not in 'CON'; 'NIR' 'SCO'; 'WAL'; 'NUK' And `<DEC>` >  31/03/2015 or Null then `<URN>` should be provided

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
Where <PL> not in ‘H5’; ‘P1’; ‘P2’; ‘P3’;
‘R1’; ‘R2’; ‘R5’; ‘T0’; ‘T1’; ‘T2’; ‘T3’; ‘T4’ ‘Z1’
And <PL_LA> not in ‘CON’; ‘NIR’ ‘SCO’;
‘WAL’; ‘NUK’
And <DEC> > 31/03/2015 or Null then
<URN> should be provided

**Comment by tab1tha** [comment]
Additional documentation

![image](https://user-images.githubusercontent.com/42181805/153033597-82ea39db-a747-4e22-97c5-e69c4c8fbe75.png)
