### ISSUE TITLE
Error code 229 (amended) - Placement provider does not match between the placing authority and the local authority code of the provider

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#130]
#### Error code
229 (amended)
#### Description to display
Placement provider does not match between the placing authority and the local authority code of the provider
#### DfE Long-form description of error
The placement provider of the episode can only be 'PR1' if the local authority code of the provider is your local authority code.  The placement provider of the episode can only be 'PR2' if the local authority code of the provider is different to your local authority.
#### DfE suggested coding
If Ofsted URN is provided and not 'XXXXXXX' then: If `<PLACE_PROVIDER>` = 'PR1' then `<LA>` must equal Ofsted URN lookup `<LA code>`. If `<PLACE_PROVIDER>` = 'PR2' then Ofsted URN lookup `<LA code>` must not equal `<LA>`.

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by PhilDeakin** [comment]
The DfE (or it might be OfSted) send us a monthly excel spreadsheet with all the valid URN codes in it, what the postcode is, what LA it's in, what PR codes are valid for the placement and all that jazz. I'm not sure what the plan is to replicate that on the website, suppose you could put the latest version in, but the codes won't remain valid over time.

**Comment by dezog** [comment]
Yeah I think this'll end up working along the same lines as the postcodes do currently, though I think those are only updated every 6 months or so. 

Main difference is AFAIK the providers details spreadsheets aren't openly available on Gov.UK, Currently having a think about how to approach this, whether DfE would be happy to add us to that list or if one or two of you analysts is up for being in charge of keeping it up-to-date? 

If we can't figure out a way to keep it in the tool & up-to-date it might prove more practical to have users upload the latest providers details file along with their data (assuming everyone that needs it will have access to it).
