### ISSUE TITLE
Error code 301 - Date of birth falls after the year ended.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#131]
#### Error code
301
#### Description to display
Date of birth falls after the year ended.
#### DfE Long-form description of error
Child's date of birth must fall on or before 31 March of the current data collection year.  Check date of birth and amend record accordingly, if the date of birth is correct, this record should be deleted from this year's submission.
#### DfE suggested coding
`<DOB>` must be `<= `<COLLECTION_END_DATE>`

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
@DMC63 are you working on this?
