### ISSUE TITLE
Error code 303 - If date Unaccompanied Asylum-Seeking Child (UASC) status ceased is not null, UASC status must be coded 1.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#133]
#### Error code
303
#### Description to display
If date Unaccompanied Asylum-Seeking Child (UASC) status ceased is not null, UASC status must be coded 1.
#### DfE Long-form description of error
Where a date UASC status ceased is recorded, the UASC field must be completed.
#### DfE suggested coding
If `<DUC>` provided, then `<UASC>` must be '1'

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by PhilDeakin** [comment]
This error code is only really relevant to data summitted as XML,  there's no UASC field for CSV. So basically as we're converting everything to CSV we might as well just close it. @dezog
