### ISSUE TITLE
Error code 334 - Date child started to be looked after in latest period of care must be on or prior to the date should be placed for adoption.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#137]
#### Error code
334
#### Description to display
Date child started to be looked after in latest period of care must be on or prior to the date should be placed for adoption.
#### DfE Long-form description of error
The date a child started to be looked after (which will either be recorded in a previous episode or in the additional start of latest period of care data item) must be prior to the date on which the local authority formally decides that a child should be placed for adoption.  Whilst an Adoption Panel may consider a case in principal before a child is looked after, no final recommendation can be made at that stage (Adoption Agency Regulations 1983 SI 1964 and circular LAC (84)3).
#### DfE suggested coding
`<DATE_INT>` must be greater than `<DECOM>` of latest episode with `<RNE>` = 'S'

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
Hello @bellt101 . This is similar to error 1003, the code here https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/pull/510/files might be of help to you.

**Comment by tab1tha** [comment]
Hello @bellt101 are you working on this?
@dezog
