### ISSUE TITLE
Error code 351 - Child was over 21 at the start of the current collection year.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#142]
#### Error code
351
#### Description to display
Child was over 21 at the start of the current collection year.
#### DfE Long-form description of error
Child must have been aged 21 or under at the start of the collection period, that is, 1 April of the current collection year.  Check that the date of birth is correct. A few young people remain accommodated in community homes up to their 21st birthday, (Section 20(5) of the Children Act (1989)) but it is not expected that they would be accommodated beyond then.
#### DfE suggested coding
`<DOB>` must be `<= 21 years prior to `<COLLECTION_START_DATE>`

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
Hi @DMC63 are you working on this?
