### ISSUE TITLE
Error code 358 - Child with this legal status should not be under 10.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#148]
#### Error code
358
#### Description to display
Child with this legal status should not be under 10.
#### DfE Long-form description of error
Where the legal status is J1, J2, or J3, date at start of legal status must be child's 10th birthday or over.  Check that the date of birth and legal status are recorded correctly.
#### DfE suggested coding
Where `<LS>` = 'J1' or 'J2' or 'J3' then `<DOB>` should `<= to 10 years prior to `<DECOM>`

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
Where `<LS>` = ‘J1’ or ‘J2’ or ‘J3’ then
`<DOB>` should <= to 10 years prior to
`<DECOM>`
