### ISSUE TITLE
Error code 104 - Date for Unaccompanied Asylum-Seeking Children (UASC) status ceased is not a valid date.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#15]
#### Error code
104
#### Description to display
Date for Unaccompanied Asylum-Seeking Children (UASC) status ceased is not a valid date.
#### DfE Long-form description of error
Date should be entered in the format DD/MM/YYYY and, if completed, should contain a valid date.
#### DfE suggested coding
If provided `<DUC>` must be in a valid format, contain a valid date and be >`= `<COLLECTION_START_DATE>`  Format should be DD/MM/YYYY.

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by jfan2006** [comment]
@mwaddoups I wonder we/ you should set a couple of global variables <COLLECTION_START_DATE>, 
<COLLECTION_END_DATE> (, and maybe others) which are used in several validation rules. 
See page 132 of the DfE validation checks document for details.

**Comment by mwaddoups** [comment]
Yes - this has been coming for a while, and will be showing up in

`dfs['metadata']['collection_start']` and `dfs['metadata']['collection_end']`

There is a related issue on the frontend for this https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta/issues/23
