### ISSUE TITLE
Error code 105 - Data entry for Unaccompanied Asylum- Seeking Children (UASC) status of child is invalid or has not been completed.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#16]
#### Error code
105
#### Description to display
Data entry for Unaccompanied Asylum- Seeking Children (UASC) status of child is invalid or has not been completed.
#### DfE Long-form description of error
Code for this data item must be either:  0 = Child was not an unaccompanied asylum-seeking child (UASC) at any time during the year; 1 = Child was an unaccompanied asylum-seeking child (UASC) at some time during the year.
#### DfE suggested coding
`<UASC>` must be provided and be a valid value  For allowed values please see associated code set.

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
@WMossDCC are you working on this?
