### ISSUE TITLE
Error code 390 - Reason episode ceased is adopted but child has not been previously placed for adoption.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#176]
#### Error code
390
#### Description to display
Reason episode ceased is adopted but child has not been previously placed for adoption.
#### DfE Long-form description of error
If reason episode ceased is coded E11 or E12 the placement code of the current episode must be A3, A4, A5 or A6. Check placement details of the adoption order.  Section13(b) of the Adoption Act 1976 provides that an adoption order must be preceded by a period of at least 13 weeks during which the child is placed for adoption with the prospective adoptive parent(s).
#### DfE suggested coding
If `<REC>` = 'E11' or 'E12' then `<PL>` must be one of 'A3', 'A4', 'A5' or 'A6'

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
Is PL the same as PL_POST ?
