### ISSUE TITLE
Error code 392b (new) - Child is looked after but no postcodes are recorded.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#179]
#### Error code
392b (new)
#### Description to display
Child is looked after but no postcodes are recorded.
#### DfE Long-form description of error
Postcodes should be completed if child is looked after unless the legal status is V3 or V4 or the child is UASC, or was formerly UASC
#### DfE suggested coding
If `<LS>` not = 'V3' or 'V4' and `<UASC>` = '0' and `<COLLECTION YEAR>` - 1 `<UASC>` = '0' and `<COLLECTION YEAR>` - 2 `<UASC>` = '0' then `<HOME_POST>` and `<PL_POST>` should be provided

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
392b is present in main. Is this one different ? Has something been changed from the original programming or can this issue be closed?.
@PhilDeakin are you aware of this already?. 
@dezog

**Comment by dezog** [comment]
well spotted, looks like this issue got duplicated - closing
