### ISSUE TITLE
Error code 407 - Reason episode ceased is Special Guardianship Order, but child has reached age 18.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#186]
#### Error code
407
#### Description to display
Reason episode ceased is Special Guardianship Order, but child has reached age 18.
#### DfE Long-form description of error
If 'reason episode ceased' is coded E45 or E46 or E47 or E48 the date current episode ceased must be before 18th birthday.
#### DfE suggested coding
If `<REC>` = 'E45' or 'E46' or 'E47' or 'E48' then `<DOB>` must be < 18 years prior to `<DEC>`

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
If `<REC>` = ‘E45’ or ‘E46’ or ‘E47’ or ‘E48’
then `<DOB>` must be < 18 years prior to
`<DEC> `
