### ISSUE TITLE
Error code 442 - Unique Pupil Number (UPN) field is not completed.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#200]
#### Error code
442
#### Description to display
Unique Pupil Number (UPN) field is not completed.
#### DfE Long-form description of error
An UPN or UPN unknown code is required for all children looked after other than those looked after under an agreed series of short- term breaks (legal status of V3 or V4).
#### DfE suggested coding
Where any episode present, with an `<LS>` not = 'V3' or 'V4' then `<UPN>` must be provided

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
Must UPN be provided even if LS is not provided? @dezog

**Comment by dezog** [comment]
I would say yes, as I reckon it's more likely that the missing LS is not V3/V4, so they will probably need to fill in the UPN too
