### ISSUE TITLE
Error code 445 - Legal status D1 cannot be started after December 2005.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#201]
#### Error code
445
#### Description to display
Legal status D1 cannot be started after December 2005.
#### DfE Long-form description of error
A legal status of D1 cannot begin after December 2005.  If a freeing order procedure was started before December 2005 and granted after that date due to court backlog, please consult DfE.
#### DfE suggested coding
Where `<LS>` = 'D1' then `<DECOM>` must be prior to 31/12/2005

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by dezog** [comment]
closed by #383
