### ISSUE TITLE
Error code 452 - Contradiction between local authority of placement code in the last episode of the previous year and in the first episode of the current year.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#204]
#### Error code
452
#### Description to display
Contradiction between local authority of placement code in the last episode of the previous year and in the first episode of the current year.
#### DfE Long-form description of error
Where a placement has not changed as at 31 March in the previous year, the local authority of placement code should match the first episode of the current year.  Check placement code, placement location code and local authority placement are correct.
#### DfE suggested coding
Where `<RNE>` of first episode in current year = `<RNE>` of last episode of previous year and `<DEC>` of previous year episode is Null then `<PL_LA>` of both episodes should be the same

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by SLornieCYC** [comment]
Hm. This and #205 seem incredibly similar to parts G and H of rule 503 (#207).  What do you think @PhilDeakin and @dezog ?  

I know Phil did parts A-F of 503 but I think parts G,H and J are still unwritten so shall I try to cover those bases at the same as these two?

**Comment by PhilDeakin** [comment]
Sounds fine to me.
