### ISSUE TITLE
Error code 514 - Data entry on the legal status of adopters shows a single adopter but data entry for the numbers of adopters shows it as a couple.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#210]
#### Error code
514
#### Description to display
Data entry on the legal status of adopters shows a single adopter but data entry for the numbers of adopters shows it as a couple.
#### DfE Long-form description of error
If reporting legal status of adopters is L0 then the genders of adopters should be coded as M1 or F1.  M1 = the single adopter is male; F1 = the single adopter is female.
#### DfE suggested coding
If `<LS_ADOPTR>` = 'L0' then `<SEX_ADOPTR>` should be 'M1', or 'F1'

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
@OgileOze are you working on this?

**Comment by OgileOze** [comment]
Hello Tambe,

I started working on it but someone mistakenly completed it. I stand to be corrected but the rule should be done. It might still be under my name though. No idea why. 

With regards,
 
Oze Ogile Madux

**Comment by dezog** [comment]
Hi Oze, 

Hope you've been well. No further updates have actually been made to this rule, the pull request is still open:
https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/pull/388

It might have caused some confusion that on the spreadsheet I've been marking as 'done' rules that have been submitted in pull requests?

Also I was meaning to reach out and ask if you're still interested in doing some rule coding? Very happy for you to finish this rule off if so! I think the PR has all the necessary changes requested.

We're also looking for people to test the tool with their own data, if you'd be up for that (i'll be sending out a group email about this soon)

All the best,
Desi

**Comment by OgileOze** [comment]
Thanks Desi. 

Yes, I’ll be fine with this and pick up a few from the the ones left if there are any. I thought it was done which is why I did not complete it. 

Happy to test with some of our data as well. I was unable to join today’s meeting as we had the Regional Meeting. 

Thank you. 

With regards,
 
Oze Ogile Madux

**Comment by tab1tha** [comment]
Great !

**Comment by dezog** [comment]
Awesome, glad to hear it. Sorry for the confusion - in retrospect I should have added a 'in progress' category...

**Comment by tab1tha** [comment]
Closed by https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/pull/388
