### ISSUE TITLE
Error code 522 - Date of decision that the child should be placed for adoption must be on or before the date that a child should no longer be placed for adoption.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#217]
#### Error code
522
#### Description to display
Date of decision that the child should be placed for adoption must be on or before the date that a child should no longer be placed for adoption.
#### DfE Long-form description of error
It must be decided that the child should be placed for adoption before the decision that a child should no longer be placed for adoption can be made.
#### DfE suggested coding
`<DATE_PLACED_CEASED>` should be `<= to `<DATE_PLACED>`

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
It must be decided that the child should be placed for adoption before the decision that a child should no longer be placed for adoption can be made.

Does this not mean <DATE_PLACED_CEASED> should be greater than(after) <DATE_PLACED>` instead?
