### ISSUE TITLE
Error code 547 - A child with health promotion information completed must also have data entries for immunisations, teeth checks, health assessments and substance misuse problem identified.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#232]
#### Error code
547
#### Description to display
A child with health promotion information completed must also have data entries for immunisations, teeth checks, health assessments and substance misuse problem identified.
#### DfE Long-form description of error
Any child who has health promotion information completed must also have immunisation, teeth check, health assessment and substance misuse problem identified fields completed.
#### DfE suggested coding
If `<HEALTH_CHECK>` provided then `<IMMUNISATIONS>`; `<TEETH_CHECK>`; `<HEALTH_ASSESSMENT>` and `<SUBSTANCE MISUSE>` must also be provided

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
Closing this because it is in main already. Appararently, someone has done it but forgot to link the issue.
