### ISSUE TITLE
Error code 554 - Date of decision that the child should be placed for adoption should be on or prior to the date that the placement order was granted.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#237]
#### Error code
554
#### Description to display
Date of decision that the child should be placed for adoption should be on or prior to the date that the placement order was granted.
#### DfE Long-form description of error
Date of decision that the child should be placed for adoption should be on or prior to the date that the placement order was granted.
#### DfE suggested coding
Where `<LS>` = 'E1' `<DATE_PLACED>` should be <= `<DECOM>` of first episode in `<PERIOD_OF_CARE>` with `<LS>` = 'E1'

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by PhilDeakin** [comment]
As this depends on knowing the period of care start I'm not sure we can replicate it. Maybe just leave this one out. @dezog
