### ISSUE TITLE
Error code 578 - The date that the child started to be missing is after the child ceased to be looked after.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#257]
#### Error code
578
#### Description to display
The date that the child started to be missing is after the child ceased to be looked after.
#### DfE Long-form description of error
The date that the child started to be missing or away from placement without authorisation should not be recorded for children who are not looked after.  Check that the missing/ away from placement without authorisation start date is whilst the child is looked after.
#### DfE suggested coding
If `<MIS_START>` >`=DEC, then no missing/away from placement information should be recorded

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
@jade-cook are you working on this? 
@dezog

**Comment by tab1tha** [comment]
This issue's pseudo code has been interpreted as:

`if (REC != X1) and (DEC < MIS_START)` then the error should be raised.
