### ISSUE TITLE
Error code 580 (new) - Child is missing when ceased being looked after but reason episode ceased not 'E8'.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#259]
#### Error code
580 (new)
#### Description to display
Child is missing when ceased being looked after but reason episode ceased not 'E8'.
#### DfE Long-form description of error
If a child is missing when they cease to be looked after on their 18th birthday, then reason episode ceased should be 'E8' (Other).
#### DfE suggested coding
If `<MISSING>` = 'M' and `<MIS_END>` = DEC and the DOB + 18 years, then `<REC>` must equal 'E8'.

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by SLornieCYC** [comment]
Rule updated in 2021 v1.2: [Children looked after return 2021 to 2022: technical specifications](https://www.gov.uk/government/publications/children-looked-after-return-2021-to-2022-technical-specifications )

If `<MISSING>` = ‘M’ **or ‘A’** and `<MIS_END>` = DEC and the DOB + 18 years, then `<REC>` must equal ‘E8’.
