### ISSUE TITLE
Error code 601 - The additional fields relating to adoption have not been completed although the episode data shows that the child was adopted during the year.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#261]
#### Error code
601
#### Description to display
The additional fields relating to adoption have not been completed although the episode data shows that the child was adopted during the year.
#### DfE Long-form description of error
Code E11 or E12 (showing that the child was adopted during the year) has been entered under reason episode ceased of the episode data submitted for this child but the fields relating to adoption have not been accordingly completed.  Check these details and either complete the missing items or amend the episode data accordingly.
#### DfE suggested coding
If 1 or more episodes `<DEC>` >= `<COLLECTION_START_DATE>` and <= `<COLLECTION_END_DATE>` and `<REC>` = 'E11' or 'E12' then `<DATE_INT>`; `<DATE_MATCH>`; `<FOSTER_CARE>`; `<NB_ADOPTR>`; `<SEX_ADOPTR>` and `<LS_ADOPTR>` must be provided

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by tab1tha** [comment]
> ## Error information
> #### Error code
> 601
> 
> #### Description to display
> The additional fields relating to adoption have not been completed although the episode data shows that the child was adopted during the year.
> 
> #### DfE Long-form description of error
> Code E11 or E12 (showing that the child was adopted during the year) has been entered under reason episode ceased of the episode data submitted for this child but the fields relating to adoption have not been accordingly completed. Check these details and either complete the missing items or amend the episode data accordingly.
> 
> #### DfE suggested coding
> If 1 or more episodes `<DEC>` >`= `<COLLECTION_START_DATE>`and`<= `<COLLECTION_END_DATE>` and `<REC>` = 'E11' or 'E12' then `<DATE_INT>`; `<DATE_MATCH>`; `<FOSTER_CARE>`; `<NB_ADOPTR>`; `<SEX_ADOPTR>` and `<LS_ADOPTR>` must be provided
> 
> For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)
