### ISSUE TITLE
Error code 632 - Date of previous permanence order not a valid value.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#274]
#### Error code
632
#### Description to display
Date of previous permanence order not a valid value.
#### DfE Long-form description of error
Date should be entered in the format DD/MM/YYYY and should contain a valid date. The date should be before the start of this current episode of care.  Acceptable value where date is not known will include zz, where zz is day, month or year value.
#### DfE suggested coding
If provided `<DATE_PERM>` should be prior to `<DECOM>` and in a valid format and contain a valid date  Format should be DD/MM/YYYY or one or more elements of the date can be replaced by zz if part of the date element is not known.

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by PhilDeakin** [comment]
Reliant on knowing the period of care start, maybe leave out. @dezog

**Comment by PhilDeakin** [comment]
Also hardly any dates get entered in the date_perm field so it won't make a massive difference anyway.

**Comment by tab1tha** [comment]
Whew, this is nice to know.

However, I started working on it so I'll just complete it.

**Comment by tab1tha** [comment]
> Reliant on knowing the period of care start, maybe leave out. @dezog

How?
The pseudocode does not include anything about checking the period of care start. Am I missing something?
@PhilDeakin

**Comment by PhilDeakin** [comment]
@tab1tha  It mentions the DECOM field... but the date_perm and decom fields are in separate files so I think it's referring to the first DECOM date in the current period of care. i.e. the period of care start. plus in the longer spiel there's "The date should be before the start of this current episode of care."

**Comment by PhilDeakin** [comment]
I suppose you could still do the valid format "dd/MM/yyyy" part of the rule.

**Comment by tab1tha** [comment]
> I suppose you could still do the valid format "dd/MM/yyyy" part of the rule.

Okay then, I have written a function to check that. It just is not passing all tests yet but it's getting there.

**Comment by dezog** [comment]
@PhilDeakin just to be sure: "current episode of care" in the description should read "current period of care"? As opposed to meaning the current (latest/ongoing) episode

**Comment by PhilDeakin** [comment]
@dezog I pretty sure it should, the previous perm file is all about children that have previously been in care, so it would made sense that the date_perm is before the current period of care start.

**Comment by dezog** [comment]
Great just thought I'd check, cheers Phil. So many of these little grey areas in the wording!

**Comment by dezog** [comment]
@tab1tha - I reckon as long as it's before the earliest episode we have, we can assume it's not an error as far as we're concerned, but for now add to the end of ErrorDefinition.description:

>"NOTE: This rule may result in false negatives where the period of care started before the current collection year"
