### ISSUE TITLE
Error code 633 - Local authority code where previous permanence option was arranged is not a valid value.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#275]
#### Error code
633
#### Description to display
Local authority code where previous permanence option was arranged is not a valid value.
#### DfE Long-form description of error
The local authority code should be a valid local authority code or one the following codes:  NIR = Northern Ireland, NUK = outside of the UK, SCO = Scotland, WAL = Wales.
#### DfE suggested coding
Where provided `<LA_PERM>` must be a valid value

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by mwaddoups** [comment]
This one is complicated and requires more work - see conversation on #295

**Comment by tab1tha** [comment]
Hi @SLornieCYC @PhilDeakin 
This issue would require a significant amount of time to implement so we are evaluating to see whether or not to prioritise it at this moment. Could you please help by answering a few questions?

- Do you use the LA_PERM field?
- What values do you put into the field (old 3 digit code? new long code?)
- Is it common to have this error (633).

Context: LA_PERM will have to be compared with the list of local authority codes and we are thinking through how that list should be gotten, stored and possibly updated.

**Comment by PhilDeakin** [comment]
@tab1tha 
Do you use the LA_PERM field? Yes, occasionally, but generally to enter our own LA code. Extremely rare that we put a different LA's code (maybe one in the past 5 years)

What values do you put into the field (old 3 digit code? new long code?) 3 digit (the guidance seems to suggest it should be the 3 digit code again this year too)

Is it common to have this error (633). No, I don't recall us having any errors of that type.

**Comment by tab1tha** [comment]
I see. Thank you @PhilDeakin .

**Comment by tab1tha** [comment]
One more question: is it possible to derive the 3 digit codes from the long codes? @PhilDeakin 
We have the long codes already (but the short codes are required, as you said).

**Comment by PhilDeakin** [comment]
@tab1tha I'm not sure sorry
