### ISSUE TITLE
Error code 146 - Placement type code is not a valid code.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#35]
#### Error code
146
#### Description to display
Placement type code is not a valid code.
#### DfE Long-form description of error
If completed, the placement type of each episode must contain a code from the range:  A3 to A6, H5, K1, K2, P1 to P3, R1 to R3, R5, S1, T0 to T4, U1 to U6, Z1.
#### DfE suggested coding
If provided `<PL>` must be a valid value  For allowed values please see associated code set.

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by jfan2006** [comment]
@mwaddoups just wanted to check with you that it's correct in the config.py it's PLACE while the DfE validation document it has PL

Looks [the technical specification](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/922285/Children_looked_after_by_local_authorities_in_England_technical_specification_to_the_2020_to_2021_data_collection.pdf) has PLACE on page 7 (CSV) and PL on page 18 (XML tag).

**Comment by mwaddoups** [comment]
Good catch on this! We'll stick with PLACE in the code, and if the user uploads an XML file we'll convert the PL to PLACE (so write your code assuming PLACE).

In general the CSV structure is the one we're working with - under the hood the Python code converts the XML to the same CSV structure. But there was a bug here you've caught which I will fix.
