### ISSUE TITLE
Error code 164 - Distance is not valid. Please check a valid postcode has been entered. [Amended 2021 v1.2]

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#350]
#### Error code
164
#### Description to display
Distance is not valid. Please check a valid postcode has been entered.
#### DfE Long-form description of error
The distance must be between 0.0 and 999.9. If the distance is unavailable, please enter this as 999.9.  This field must be completed for all placements, active or beginning after 31 March 2015, unless the legal status is V3 or V4 (looked after under an agreed series of short-term placements - respite). **or the child is UASC or formerly UASC.** 
#### DfE suggested coding
**If not (`<UASC>` = '1' or `<COLLECTION_YEAR>` -1 `<UASC>` = '1' or `<COLLECTION_YEAR>` -2  `<UASC>` = '1') and** if `<LS>` not = 'V3' or 'V4' then `<PL_DISTANCE>` must be between '0.0' and '999.9'  Note: `<PL_DISTANCE>` is a calculated value based on Postcode.

For further info, refer to the DfE validation document [here](https://www.gov.uk/government/publications/children-looked-after-return-2021-to-2022-technical-specifications)

**Comment by tab1tha** [comment]
This goes against the definition of https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/issues/185 @dezog
