### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by PhilDeakin** [data-to-insight/csc-validator-be-903#355]
https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/blob/bdf35e4d88946b83abe040865db829afbb26aead/validator903/validators.py#L37

The line is mistyped.   Should be   'collection_end'

**Comment by dezog** [comment]
Well spotted! Fixed by https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/commit/757f526b4621e1fda7b24fbaf15f5a61fc384c32
