### ISSUE TITLE
Error code 165 - Data entry for mother status is invalid.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#45]
#### Error code
165
#### Description to display
Data entry for mother status is invalid.
#### DfE Long-form description of error
Code for this data item must be either:  0 = Female child is not a mother, 1 = Female child is a mother.  This field should indicate whether the child was a mother or not on 31 March and must be completed for all female children looked after during the year ending 31 March of the current collection year (unless the child is being looked after under an agreed series of short term placements â€“ legal status V3 or V4).  This field should be left blank and not recorded as 0 for male looked after children. This field should be left blank for care leaver with no episode information recorded for this collection year.
#### DfE suggested coding
If provided `<MOTHER>` must be a valid value
If not provided `<MOTHER>` then either `<GENDER>` is male or no episode record for current year and any of `<IN_TOUCH>`, `<ACTIV>` or `<ACCOM>` have been provided

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by jfan2006** [comment]
Hi @mwaddoups , this rule has been amended in the linked document version 1.3. There are extra bits for coding rule and coding description.

**Comment by tab1tha** [comment]
@dezog the comment above
