### ISSUE TITLE
Error code 392b - Child is looked after but no postcodes are recorded. [Added 2020 v1.1]

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#465]
**Note: This one appears to have been missed from the git issues list!**

#### Error code
392b
#### Description to display
Child is looked after but no postcodes are recorded.
#### DfE Long-form description of error
Postcodes should be completed if child is looked after unless the legal status is V3 or V4 or the child is UASC, or was formerly UASC
#### DfE suggested coding
If `<LS>` not = ‘V3’ or ‘V4’ and `<UASC>` = ‘0’ and `<COLLECTION YEAR>` -1 `<UASC>` = ‘0’ and `<COLLECTION YEAR>` -2 `<UASC>` = ‘0’ then `<HOME_POST>` and `<PL_POST>` should be provided

For further info, refer to the DfE validation document [here](https://www.gov.uk/government/publications/children-looked-after-return-2021-to-2022-technical-specifications)

**Comment by dezog** [comment]
Thanks for this @SLornieCYC ! Problem is the git issues were scraped from the 2019 file, i believe
