### ISSUE TITLE
Error code 197b - SDQ score or reason for no SDQ should be reported for 4-or 17year-olds [Added 2021 v1.2]

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#469]
**Note: This one appears to have been missed from the git issues list!**

#### Error code
197b
#### Description to display
SDQ score or reason for no SDQ should be reported for 4-or 17year-olds
#### DfE Long-form description of error
For children aged 4-or 17-years-old at the end of the year, who have been continuously looked after for at least 12 months, either a SDQ score, or a reason for no SDQ score should be provided. Both of these should not be left blank. If the child was aged 3-years-old or 17-years-old at their last assessment, then report SDQ1 as the reason.
#### DfE suggested coding
If `<CONTINUOUSLY_LOOKED_AFTER >` = ‘Y’ and either: 
  i) `<DOB>` = 4 years prior to `<COLLECTION_START_DATE>` or 
  ii) `<DOB>` = 17 years prior to `<COLLECTION_START_DATE>` 
Then either `<SDQ_SCORE>` or `<SDQ_REASON>` should be provided

For further info, refer to the DfE validation document [here](https://www.gov.uk/government/publications/children-looked-after-return-2021-to-2022-technical-specifications)

**Comment by dezog** [comment]
I added this yesterday (d0fb1f88888166d8c406ab1cdea4c195c97c2bf3) but I don't think what I've done is right - a bit confused by the descriptions here. 

- Is it saying they should be 4 or 17 years old at the start of the year or end of the year? 
- Coding description says ) '<DOB> = 4 years prior' but I guess they mean like 4th bday to the day before 5th bday?

@SLornieCYC @PhilDeakin @bellt101 @Steve-Far -- let me know if you can make sense of this one!

**Comment by bellt101** [comment]
The SDQ is a questionnaire given to all children who are aged between 4 and 16 so after their 4th birthday and before their 17th birthday.

With best wishes

Tracy

**Comment by dezog** [comment]
Thanks Tracy, 

that sounds like rule 186:

> Children aged 4 or over at the start of the year and children aged under 17 at the end of the year and who have been looked after for at least 12 months continuously should have a Strengths and Difficulties (SDQ) score completed. 

This one sounds like it's trying to get at something subtly differnt but not explained very well. Exactly 4 OR exactly 17? Word description says end of year, code description says start?

**Comment by dezog** [comment]
....basically this is one for emailing DfE, isn't it 😅

**Comment by SLornieCYC** [comment]
See page 103-105 in the return guide (separate from validation definition): https://www.gov.uk/government/publications/children-looked-after-return-2021-to-2022-guide

I *think* this is trying to capture rows 2 and 4 (EDIT: and 5?) from the table at the end of page 104 (in which case I'd argue the code description is wrong and should be <COLLECTION_END_DATE>).

**Comment by dezog** [comment]
Ah, that must be it. Thanks both, much appreciated! 🙏

**Comment by tab1tha** [comment]
I have changed the comparison such that collection_end is the reference point (instead of collection_start), based on your conversations. The pull request is linked.
