### ISSUE TITLE
Mystery IndexError issue

### ISSUE THREAD

**Issue by dezog** [data-to-insight/csc-validator-be-903#473]
We've had a report from someone trying to upload an XML file and the tool failing with an IndexError. They say it worked last month, so it seems likely to be related to the recent updates.

Unfortunately, the resulting error message is not massively informative:

> We ran it last month and it provided a helpful output of our errors this year to date, however I’ve just tried running it again today and it displays the following error message:
> 
> <img width="571" alt="image004" src="https://user-images.githubusercontent.com/63907524/143915062-c0763822-19a7-4879-b9ba-b5ddd6099919.png">
>
> I wondered if there was an issue with today’s XML file, so I input the file which ran successfully last month and this one also produces an error:
>
> <img width="597" alt="image005" src="https://user-images.githubusercontent.com/63907524/143915033-9cc53d04-f4cb-4fdc-af52-5fcac79dcec2.png">

**Comment by dezog** [comment]
This has been tracked down to errors 352, 387 & 389 - thanks @Steve-Far 

Looks like a boolean mask from a merged dataframe being used on the original dataframe of different length

**Comment by SLornieCYC** [comment]
Weird.  The merged Episodes dataframe ought to be the same length as the original Episodes dataframe as it's only left-joining with Header - and you would only expect that to have one record per child.  Will update tests and swap the location to get unique index from the merged dataframe.

**Comment by dezog** [comment]
> Weird. The merged Episodes dataframe ought to be the same length as the original Episodes dataframe as it's only left-joining with Header - and you would only expect that to have one record per child. Will update tests and swap the location to get unique index from the merged dataframe.

Yeah, in theory! 😕 I guess this goes back to what you raised in https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/issues/347 - we should have some basic pre-validation integrity checks for this sort of thing, as they're often assumed throughout the code, and could potentially also be causing more subtle issues somewhere or other.
