### ISSUE TITLE
Bug: sometimes you appear to get datetime.datetime objects in DEC column

### ISSUE THREAD

**Issue by dezog** [data-to-insight/csc-validator-be-903#519]
**Describe the bug**
Sometimes you get DEC's appearing like `datetime.datetime(2020, 5, 20, 0 , 0)`
Appears to only affect the DEC column. 

**To Reproduce**
Upload episodes data. Look through Episodes data in Error Display screen of site.
Has been observed with fake data and real 903 data, affecting both CSV & XML formats

**Expected behavior**
All dates should appear as they do in the uploaded text files

**Screenshots**
![image](https://user-images.githubusercontent.com/63907524/145581978-8c86bcf2-ad44-4b50-b1aa-4e5998f3f346.png)

**Comment by tab1tha** [comment]
![image](https://user-images.githubusercontent.com/42181805/146159850-bdfb380a-9c63-48e8-9b81-8953483504de.png)
That's strange, DEC is not one of the fields that error 181 is supposed to check for (see the code attached).
Does this happen with all DEC values in the file?

**Comment by dezog** [comment]
I think it's unrelated to rule 181, and the child just happened to have that error. 

It doesn't happen for all DEC's; at one point I thought it was only happening for the final row of Episodes table, but I'm not entirely sure about that. 

Currently I can't seem to reproduce the bug with the fake data

**Comment by tab1tha** [comment]
I see

**Comment by tab1tha** [comment]
This might be useful https://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable and this https://realpython.com/python-datetime/#creating-python-datetime-instances

**Comment by dezog** [comment]
Closing as noone's reported seeing this one in some time; we think it's probably fallen out somewhere along the way

**Comment by tab1tha** [comment]
This has not shown up for a while. It must have been fixed as part of one of the updates.
