### ISSUE TITLE
Bug: Rule 180 - wrongly flagging null values

### ISSUE THREAD

**Issue by dezog** [data-to-insight/csc-validator-be-903#520]
Describe the bug
@Steve-Far reports rule 180 is flagging null values for children looked after for 12 months

**To Reproduce**
validate OC2 data where SDQ_SCORE is null

Expected behavior
Null values should not trigger 180

**Comment by dezog** [comment]
Is anybody able to reproduce this? The code appears to be explicitly excluding null values, and `pd.NA` in the test data is passing 

@steve-far 
![image](https://user-images.githubusercontent.com/63907524/145860924-561cb0b0-edbc-4a15-86d5-fbdb4bd3c7ea.png)

**Comment by Steve-Far** [comment]
@dezog Hi Desi, I have just rerun my XML through the tool and this error is no longer being flagged??

**Comment by dezog** [comment]
Hi Steve, that's weird! But 181 still is? 😕

**Comment by Steve-Far** [comment]
Yes, I ran last years xml, this years (YTD) and then combined. 180 isn't showing as an error but 181 is....
![image](https://user-images.githubusercontent.com/92323914/146023546-aee788a6-8e8d-426f-9e31-db20553ad8f3.png)

![image](https://user-images.githubusercontent.com/92323914/146023715-2d8ba1f5-cc6b-47fa-8c7b-f1e9f2d96922.png)

**Comment by tab1tha** [comment]
Can we say that this is resolved then?. Can this error be closed?

**Comment by Steve-Far** [comment]
> Can we say that this is resolved then?. Can this error be closed?

I think so, yes.
