### ISSUE TITLE
Bug: Rule 399

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#546]
**Describe the bug**
This rule is triggering on all children with any `<LS>` = V3/V4 episode whereas I think that should only happen when the child does not have any other `<LS>` recorded in-year.

**To Reproduce**
- Upload 'Episodes' and 'Header CSV's, where:
   - 'Header' contains a child with `<MOTHER>` filled in.
   - 'Episodes for same child has one placement with `<LS>` = V4 and one placement with e.g. `<LS>` = V2 (any non-V3/V4 code).
   - Rule 399 is triggered.

**Expected behavior**
Where child has more than one episode in-year that include both `<LS>` = V3/V4 and any other non-V3/V4 `<LS>` this rule should not trigger.  As it currently stands Rule 399 is incompatible with Rule 393.

![image](https://user-images.githubusercontent.com/89449804/150354662-f142766d-7ffb-442a-8038-939454d4fc22.png)

**Comment by dezog** [comment]
I see what you mean - this one should only be for children who ONLY have V3/V4 episodes

**Comment by dezog** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [399:](https://trello.com/c/kL6DBiZo/144-399)

**Comment by tab1tha** [comment]
Can we also say that if the child has episodes with LS==V3 or V4 and other episodes where LS is not provided (NaN), then this error should not be triggered?. 
Must the other value be an actual value or is a NaN sufficient to quench the rule (error code 399 should not be triggered).
@SLornieCYC @dezog

**Comment by dezog** [comment]
I would say this error would most likely end up being a red herring if they've just forgotten to put the LS in for an episode, so only trigger this if every episode for a child is V3/V4

It would be annoying to delete those items then realise the missing code wasn't V3/V4!
