### ISSUE TITLE
Bug: Rule 433 - saying corresponding DECCOMs & DECs don't match when they do

### ISSUE THREAD

**Issue by dezog** [data-to-insight/csc-validator-be-903#547]
**Describe the bug**
User reports that continuation episodes start and end dates appear to be in order but are getting flagged:

![image](https://user-images.githubusercontent.com/63907524/150381696-e7d1e38b-0f49-4051-b4c6-4f957519ab98.png)

**To Reproduce**
Unable to reproduce. Results appear to make sense for test data, in that it happens where there are multiple concurrent episodes:
![image](https://user-images.githubusercontent.com/63907524/150382178-75bf2004-d746-481d-b9bb-9707944c4ee2.png)

**Expected behavior**
If sorted by DECOM, if DECOM is the previous row's DEC, it should not be an error.

**Proposed fix**
Could be an off-by-one thing where something like one child having a duplicated DECOM throws the whole thing off

**Comment by dezog** [comment]
I'm wondering if this could be share a cause with the 'continuously looked after' check not working properly for rule 187

**Comment by tab1tha** [comment]
This came up again on something else I'm working on. It seems that DEC dates are shortened when they are read in using pd.read_csv() but DECOM dates are not. Screenshots attached.

THIS IS SYNTHETIC DATA

Viewing the csv files in excel, both have full year values.
![image](https://user-images.githubusercontent.com/42181805/158563011-5d52f1f9-ef9f-4f43-8a39-d2cba6253c9e.png)
When read into a DataFrame:
![image](https://user-images.githubusercontent.com/42181805/158563185-a71158bf-4291-4b08-a866-97be44e22499.png)

**Comment by tab1tha** [comment]
This might be because NaN values are present in the DEC column but not in the DECOM column.
![image](https://user-images.githubusercontent.com/42181805/158569073-3136e211-653b-4708-847c-e0ae1e64a5d3.png)

**Comment by tab1tha** [comment]
This solved it.
![image](https://user-images.githubusercontent.com/42181805/159510022-0dc3cf33-085f-4b17-b05f-7002f3a3b53d.png)

@dezog is it worth putting a function like this in the ingress file?. It transforms the dates back to their original string formats and leaves NaNs undisturbed.

Still, there might be a better way to go about it.

**Comment by dezog** [comment]
i think your episodes csv's got the wrongly formatted dates from a bug that was in the synthetic 903 generator where the DEC column was output as dd/mm/yy instead of dd/mm/yyyy, causing the `to_datetime` to return a column of just nan's

that's fixed now, but this issue seems to have been caused by something else, as it was happening with real data despite the dates looking right

i think we can close this issue now anyway, as it's not been seen since around jan/dec, and a lots changed in the meantime so hopefully its fixed.

cool method for inserting stuff into a list btw!
