### ISSUE TITLE
Bug: Column Header Mismatch

### ISSUE THREAD

**Issue by CeeJay68** [data-to-insight/csc-validator-be-903#548]
I am experiencing an issue loading my 'placed for adoption' file. I load the files in and keep getting the error below.
However my file is using the correct header, as below;

![Error](https://user-images.githubusercontent.com/89516354/150787177-43c60ac0-672e-4288-b1c4-6e8802a3d278.png)

![File Header](https://user-images.githubusercontent.com/89516354/150788466-4b2f4710-488d-4bc9-b965-b2f518513dad.png)

**Comment by dezog** [comment]
Hi @CeeJay68, looks like a typo here - `REASON_PLACE_CEASED` should be `REASON_PLACE<D>_CEASED` 

Thanks for bringing this up though, it would definitely be better for the error message to be a bit more specific, I know things like this can be a real pain. I'll create an issue for this, though we've currently a bunch of stuff to get done before we'll be able to get to it!

**Comment by dezog** [comment]
Closing this as I've created new issue here: https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/issues/549 Thanks again for this - don't hesitate to report any further bugs/niggles/feedback!
