### ISSUE TITLE
Error code 178 - Placement provider code is not a valid code.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#55]
#### Error code
178
#### Description to display
Placement provider code is not a valid code.
#### DfE Long-form description of error
If completed placement provider of each episode must contain a code from the range PR0 to PR5.  The placement provider code should be left blank if the record is only recording the young person's activity and accommodation after leaving care.  The placement provider code should be left blank for children in any of the following placements: T0, T1, T2, T3, T4 or Z1.
#### DfE suggested coding
If provided `<PLACE_PROVIDER>` must be a valid value and should not be provided if `<PL>` = 'T0'; 'T1'; 'T2'; 'T3' or 'Z1'.  For allowed values please see associated code set.

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by jfan2006** [comment]
I think the DfE validation document has a little error here - it should include 'T4' in the 'coding description'.

**Comment by jfan2006** [comment]
But also here it uses 'should not be provided' (rather than a 'must') - so I wondered we need to ignore this bit "and should not be provided if <PL> = 'T0'; 'T1'; 'T2'; 'T3' or 'Z1'." ?
-----
EDIT: I think I was wrong about this... as it looks many coding descriptions do use 'should'.
