### ISSUE TITLE
Bug: Rule 208 - Unknown UPN's becoming known shouldn't trigger this error

### ISSUE THREAD

**Issue by dezog** [data-to-insight/csc-validator-be-903#552]
**Describe the bug**
a helpful LA noticed this error triggering on validated csv's downloaded from the DfE portal, where a child had UN5 code for the UPN field last year's header but it had been filled in in the current year.

They did not expect to see this, as the DfE portal doesn't complain about this error in that case, despite the guidance's claims:

![image](https://user-images.githubusercontent.com/63907524/151375900-eaa04dce-415a-4e83-95b2-9f7cd0a08758.png)

@PhilDeakin @bellt101 @Steve-Far @SLornieCYC is anyone able to confirm this?

**Proposed fix**
change so that if unknown UPN code last year but valid UPN this year, it's not an error

**Comment by PhilDeakin** [comment]
I think it's expecting us to change the previous year's UPN from UN1-5 code to a full 13 character UPN if we now have it this year. The error really relates to the previous year, not this year.

**Comment by tab1tha** [comment]
Can we say a solution will be to make sure that if the previous year's UPN is UN1-5, then the error is not raised? @PhilDeakin 

Right now, it is okay to move from a known UPN to an unknown UPN. However, this clause will add that it is also okay to move to an unknown UPN to a known one.

`error_mask = in_both_years & upn_is_different & ~upn_not_recorded & upnprev_not_UN1-5 `

What do you think?.

**Comment by PhilDeakin** [comment]
@tab1tha Yeah, sounds okay to me.

**Comment by dezog** [comment]
> I think it's expecting us to change the previous year's UPN from UN1-5 code to a full 13 character UPN if we now have it this year. The error really relates to the previous year, not this year.

Yeah I guess this is the main point - it's not a problem with the current year's data, so it's not our problem. We basically assume last year's data is already validated through the DfE portal; and even if last year's data does need updating, it'll still need updating on DfE's system when it opens up.

By the way - is UN6 is real? It's mentioned in this rule's description but nowhere else - pretty sure it is a typo?

![image](https://user-images.githubusercontent.com/63907524/152144279-7190c9e9-8e56-462c-97e9-f15d51596160.png)

**Comment by PhilDeakin** [comment]
You're right, UN6 isn't a valid option.

**Comment by SLornieCYC** [comment]
Interestingly the DFE portal also **doesn't** appear to trigger 208 if the current-year UPN is null even if the previous year had a UPN recorded.  The current implementation of rule 208 here **does** trigger in that circumstance however.  

Undecided whether we should change the rule here to match DFE implementation or leave the existing behaviour intact as an enhancement.  Rule 442 (no UPN recorded) does trigger on these anyway, but I'm thinking having 208 as well helps users distinguish between "not recorded at all" and "missing but exists elsewhere".
