### ISSUE TITLE
Bug: Rule 185, 190, 198 - Ongoing issues with continuously looked after

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#568]
Continuation of problems with this calculated field (post https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/commit/7c1177887656b9cf2db63af89cb537ef10a96550 which I think has been implemented on 903.datatoinsight.org?): 

All children included in my OC2 file are flagging as in-error due to having these data populated while supposedly not being continuously looked after - but the episodes data show that they **have** been continuously looked after.

**Expected behavior**
Children who have been continuously looked after should not be flagged as errors on rules 185, 190 or 198 when they have the respective OC2 data.

**Screenshots**

![image](https://user-images.githubusercontent.com/89449804/154297433-c8f424f5-e368-4f39-9176-7b874e22c26e.png)

![image](https://user-images.githubusercontent.com/89449804/154297311-3cdc1317-0957-4212-97ae-48f2321e8505.png)

**Comment by dezog** [comment]
This is concerning! I'm not sure what's causing it, it doesn't look like similar episodes are triggering it from within python (note the rule returns index 1 corresponding to CHILD '2'):

![image](https://user-images.githubusercontent.com/63907524/154310750-f3c9199e-7ef0-4635-bd89-92379a3b2817.png)

**Comment by dezog** [comment]
I'm going to set up some more detailed logging and run some files through, hopefully that'll shine a light on what's going on!

**Comment by dezog** [comment]
had to get right in there but i've figured it out. 

the collection start/end in metadata are currently datetime.datetime objects, not strings, and for some reason, when `pd.to_datetime` is called on those, it results in a null value. weirdly, this seems to happen in the site itself, but not when running the Python locally, despite running the same pandas version 1.0.5

![image](https://user-images.githubusercontent.com/63907524/154485798-0faa8123-086b-4324-b835-25ffc92f4b67.png)

**Comment by dezog** [comment]
in theory this could be breaking every rule with a collection start/end comparison, which would be bad. Those don't seem to have been showing up though, unless I'm mistaken. 

In any case, just changing the values in metadata to be strings should fix this - just have to make sure none of the rules rely on them being datetime values already. I don't think that should be the case though as none of the tests in test_validators use datetimes

**Comment by dezog** [comment]
this here makes absolutely no sense to me 🤷 , seems like a bug

![image](https://user-images.githubusercontent.com/63907524/154496601-324dc676-a138-41b4-98ad-8495dc69b217.png)

but anyway, i've made the change and it _appears_ to work (🤞) , so that'll make its way to the live tool either tomorrow or early next week -- hopefully that puts this one to bed for good this time!
