### ISSUE TITLE
Bug: Rule 434 - false positives

### ISSUE THREAD

**Issue by dezog** [data-to-insight/csc-validator-be-903#578]
**Describe the bug**
this rule is producing errors where there appears to be nothing wrong with the data - LS different; everything else the same

**To Reproduce**
Not sure without access to the data but it was quite common, i'd expect running any actual 903 data through the tool would result in this bug showing up

**Comment by SLornieCYC** [comment]
Can replicate.  Appears to only be a problem where one of columns being compared has null values in both rows (e.g. episodes where child is placed with parent PR0 and URN is therefore not required).
