### ISSUE TITLE
Bug: Rule 131, 132 & 133 - NULL values should trigger error

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#579]
**Describe the bug**
At the moment this rule ignores null data in 'IN_TOUCH' (131), 'ACTIV' (132) and 'ACCOM' (133).

**Expected behavior**
Null data in 'IN_TOUCH', 'ACTIV' and 'ACCOM' should trigger these errors.  This is the behaviour in the DFE portal for CSV source files.

**Proposed fix (Optional)**
Delete the following from the masks:

```| care_leavers['IN_TOUCH'].isna()``` (131)

```| care_leavers['ACTIV'].isna()``` (132)

``` ~oc3['ACCOM'].isna() &``` (133)

Note: This is relevant to CSV source files where a child is included in the file and then has null data, but not sure on the behaviour/impact for XML source files: that probably depends on how the XML is structured/produced (are the relevant fields included when null or not relevant?) and parsed by this tool into the dataframes (i.e. will there be an OC3 record with NULLs for every child in Header, or is the OC3 dataframe only populated for records with any OC3 data?).

**Comment by SLornieCYC** [comment]
~~This also applies to rule 153 for CSV source files - if the child is in the OC3 file (and therefore dataframe in this tool) then null data in any **or** all of 'IN_TOUCH', 'ACTIV' and 'ACCOM' should trigger the error.  Again not sure on how this needs to function for XML source files.~~

On second thought this rule is probably okay as-is because the other rules will flag up nulls.

**Comment by SLornieCYC** [comment]
As mentioned in #584 this will now work correctly for CSV source files however if XML source files need to differ the rule logic can be extended to branch based on the 'file_format' value in metadata.

**Comment by tab1tha** [comment]
Great @SLornieCYC !
I'll look through.
