### ISSUE TITLE
Query: Rule 213 - Does not appear to trigger on Z1 in DFE portal

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#580]
**Describe the bug**
Per validation rule documentation this rule has been coded to apply to T0-4 and Z1 placement types, however in the DFE portal this rule does not appear to trigger on Z1 placements.

**Expected behavior**
Not sure whether the rule is working as expected on T placements as we have opted not to use these optional codes locally, however assuming it **is** working for those that leads to the question: Should we follow the DFE guidance documentation (current implementation) or amend the rule to match how it actually appears to work in the DFE return portal for Z1 placements?

**Comment by dezog** [comment]
Interesting - this sounds like the same thing discussed in https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/issues/551, where analysts from another LA reported getting errors on Z1 placements unexpectedly. 

If the DfE portal doesn't report errors for these, I'd tend toward doing the same

**Comment by dezog** [comment]
fixed by fb71f2dad1e95b47cb85952d90b60b6bdedd3b6f
