### ISSUE TITLE
Bug: Rule 1007 - CLA Portal does not match DFE guidance

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#591]
**Describe the bug**
The behaviour of this rule in the DFE CLA portal does not appear to match the coding description in DFE's validation rule guidance document (and which has been used to code this rule in this D2I validation tool).  This means that means although we're following the DFE guidance, errors flagged here are different to those that LA users will find in their actual CLA returns.

**Expected behavior**
From observation of records in the DFE CLA portal the rule appears to function more in line with the validation rule description/message, being related to whether the child (aged 17-18) was still in care on the day after their in-year birthday.  I have raised a service request with DFE asking for clarification of the correct coding description - will report back if I hear anything more!

**Comment by SLornieCYC** [comment]
Response from DFE below.

> I think it most straightforward to interpret this rule by reference to the children looked after data collection guide (version 1.3).  The guide states that 
>  
> "For young people who turned 17 or 18 during the latest year, care leaver information is required if they left care before or on their birthday (for example, if a young person turned 17 or 18 in the latest year and left care before their 17th or 18th birthday then care leaver information is required; or if a young person left care on their 17th or 18th birthday in the latest year, then care leaver information also is required).  However, if the young person is still in care on their 17th or 18th birthday, then care leaver information is not required.  For example, if a young person turned 17 or 18 in the year, and was in care on their 17th or 18th birthday, but left care the day after, then we do not require care leaver information for this young person"
>  
> This is the guiding principle and confirms the following statements:
>  
> •	date of birth is between 1 April 2004 and 31 March 2005;
> •	We would expect that a child who doesn't leave care until after their 17th or 18th birthday, would trigger 1007 if the care leaver details are completed; and 
> •	Conversely, care leaver information should be provided if the child is still in care on their 17th or 18th birthday.

**Comment by dezog** [comment]
Hey @SLornieCYC, I've created a [pull request ](https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/pull/596)to fix this, would you mind taking a look to see if it agrees with your understanding of the DfE explanation?

**Comment by dezog** [comment]
By the way, thanks so much for the legwork you've done on all these issues, incredibly helpful for us and for users of the tool!

**Comment by tab1tha** [comment]
> By the way, thanks so much for the legwork you've done on all these issues, incredibly helpful for us and for users of the tool!

I agree.
Thank you @SLornieCYC  !

**Comment by tab1tha** [comment]
Since the related pull request (https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/pull/596) has been merged, can we now close this issue? @SLornieCYC @dezog

**Comment by SLornieCYC** [comment]
I think that makes sense.  If any further problems are identified they can be logged in a new issue.
