### ISSUE TITLE
Bug: Rule 503[*] - Inconsistent with coding description/CLA Portal

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#592]
**Describe the bug**
As currently written validate_503_Generic requires the first episode of the current year and the last episode of the previous year (for the same child) to have the same DECOM value when comparing data, whereas the DFE validation guidance and portal work on comparing the first and last episodes only when the last episode has no DEC (irrespective of DECOM).  This means some episodes are not being picked up in this tool when they are in the DFE CLA portal.

**Expected behavior**
The rules should compare the first episode of the current year with the last episode of the previous year (with no DEC) for the same child, even when the DECOM is different.

**Proposed fix**

1) Remove DECOM from the on= clause in this line:

`merged_co = min_decom.merge(max_last_decom, how='inner', on=['CHILD', 'DECOM'], suffixes=['', '_PRE'])`

2) Add a check for `merged_co[DEC_PRE].isna()` to the mask in the following two lines:

`err_mask = abs(merged_co[this_one].astype(float) - merged_co[pre_one].astype(float)) >= 0.2`

`err_mask = merged_co[this_one].astype(str) != merged_co[pre_one].astype(str)`

**Comment by dezog** [comment]
Should be fixed by https://github.com/SocialFinanceDigitalLabs/quality-lac-data-beta-validator/commit/8fbce967bdd3c5c8151602a17f637bbff3552399
