### ISSUE TITLE
Bug: Rule 574 - Sort order affecting in-error record

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#594]
**Describe the bug**
Depending on how the dates of Missing records overlap sometimes the validation tool is highlighting a different record to that returned by the DFE CLA Portal. I think this is due to different sort orders being applied to the records in the dataset.

**Expected behavior**
The validation tool should return the same record in-error as the CLA Portal.

**To Reproduce**
In the example below, the Missing records are ordered by MIS_START and the record highlighted in-error is the one starting on 08/06/21 where MIS_START is before the preceding MIS_END (03/08/21 - a clear case of mistyped date).  In the CLA Portal records appear to be sorted by **MIS_END** and then by MIS_START, with the record in-error being the one starting on 03/06/21 where MIS_START is still before the preceding MIS_END (09/06/21).

**Screenshots**
![image](https://user-images.githubusercontent.com/89449804/162985027-8bffedfb-36b2-4fda-b036-9ea9ed5257ba.png)

**Proposed fix**
The following line should be amended to insert MIS_END before MIS_START (default sort-order will put null MIS_ENDs last):

`  mis.sort_values(['CHILD', 'MIS_START'], inplace=True)`

**Comment by dezog** [comment]
Been taking a look at this one, and I've come to the conclusion that we can't necessarily tell which date is mistyped. 

I'm thinking what would be best is either: 
- to just highlight both rows where two overlap (though it might not be obvious only one row actually has an error)
- or, to leave it as it is and assume that the description makes it clear enough that people can figure out where the actual error is

**Comment by SLornieCYC** [comment]
I agree the tool can't determine which date is wrong, but that's really down to the LA analyst to figure out anyway.  Here I'm just trying to get to a place where the tool to behaves consistently with the DFE portal in terms of the record that gets flagged as in-error (sort order), because at the moment that's not always the case.  Highlighting both affected rows would be another step away from DFE portal behaviour and, as you say, wouldn't necessarily make clear where the error is.

**Comment by SLornieCYC** [comment]
Created branch on Replit to fix the sort order but that hasn't appeared on Github yet for me to create a PR.

![image](https://user-images.githubusercontent.com/89449804/177736753-c8482142-c7dd-49e1-ab71-1b4941028ce6.png)

**Comment by SLornieCYC** [comment]
Figured it out.  Apparently Replit has changed something since I last used it earlier in the year - now have to create branch, commit changes _**and then**_ Push the branch before it turns up on Github!
