### ISSUE TITLE
Bug: Rule 1009 - <REASON_PLACE_CHANGE> must  be a valid value

### ISSUE THREAD

**Issue by SSwas** [data-to-insight/csc-validator-be-903#595]
**Describe the bug**
We are getting the error triggered for all except 4 entries where we have add the “REASON_PLACE_CHANGE” code. All “REC” column populated with “X1”.

**Expected behavior**
How this rule should behave instead- no error are should be expected as code used is in list.

**Comment by tab1tha** [comment]
Thank you @SSwas 
The non-blank entries that flagged the error did not seem to have any significant similarities. It is not yet clear how to replicate this error.

We'll look into it.

**Comment by SSwas** [comment]
I am closing this “issue” as its not an issue but a user error. 
Long version: It transpires that the during the compilation of the episode file – the “REASON_PLACE_CHANGE” is obtained via a lookup from a Mosaic report which require the fx Left(cell, 6) to use be used.  As one of the codes ( CUSTOD) is 6 character long, all the other codes (5 char) are returned with a space so this does not exact match the “codelist”. The reason why 4 entries did not encounter the an error is that one record was ( CUSTOD) and the 3 others where typed in manually.
Many thanks again for developing this valuable tool.
