### ISSUE TITLE
full repo refactor: irregularities spotted.

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/csc-validator-be-903#654]
This issue will be used to track any anomalies that have been spotted in the codebase which might need to be addressed after the refactoring process is done.
- The priority of the refactoring process is to ensure that no logic is changed.
- Any logic changes that cannot be postponed will be done and their effects tracked here.
- In this discussion, the current/old tool will be referred to as _the 903 tool_ and the tool built on the new codebase  will be referred to as _the lac tool_.

Log:

- the number of rules being run in the live 903 tool is one less than the number of rules that are coded. The EPI rule exists in validators.py but is not being run because [it was removed from config.py](https://github.com/data-to-insight/quality-lac-data-beta-validator/commit/c4e2e42f2a3a40c13d7344bfdc6f066b5d54f674).
- [x] Hence, it was added into the main branch (old codebase) so that the comparison between the new and old codebases is done between the same number of rules.
- The groupby in rule632 raised the error "attempting to get argmin of empty sequence". It was also seen to fail on main (it slipped through the github actions filter)
- [x] Invalid/empty DECOM dates have been dropped before the groupby in both old and new codebases.
- The old codebase used a hardcoded list of rules, called `configured_errors`, to generate the report that the user downloads. This tight coupling meant that a new ruleset could not easily be swapped into report generation.
- [x] ruleset is being passed in as a parameter to the Report class in report.py. It has been confirmed that this change does not affect the report result. 

> at the time of this writing, the report generated by running the header and episodes files in the fake_data folder, using Richmond as local authority is 72 rows for error_summary and 34557 rows for child summary. error_summary maps to the ErrorCounts file and child_summary maps to the ChildErrorSummary file in the live tool.

**Comment by SLornieCYC** [comment]
I think EPI not being in config.py is an oversight (the rule should be run).  The rule was deleted in #587 (both from validators.py and config.py) but then re-added to validators.py in the next commit on the same PR - it looks like config.py was just missed from the second commit.

**Comment by tab1tha** [comment]
Thank you for pointing this out @SLornieCYC .
I spotted the commit but couldn't see the pull request it came from so missed the surrounding context. Reading through the conversation in the PR explains it now. 
Thank you !

**Comment by tab1tha** [comment]
The migration from old codebase to new is now complete. Immediate outputs from the validator and the user reports produced by both codebases were compared at multiple points. 
Both codebases produced the same result. 

The refactoring process is done.

**Comment by tab1tha** [comment]
One thing to add is that datetime conversion was not centralized in the 903 tool because some rules expect the dates as strings.
For example rule [632 expects date values to have zz](https://github.com/data-to-insight/quality-lac-data-beta-validator/issues/274) in them as placeholders for unknown values. If datetime conversion is done centrally and before the validation process, all those dates will be marked as invalid.

**Comment by tab1tha** [comment]
The scripts used to run through the code and do the initial mass transformations can be found in the [debug_n_repo_transform_scripts folder](https://github.com/data-to-insight/quality-lac-data-beta-validator/tree/main/documentation/debug_n_repo_transform_scripts).

**Comment by SLornieCYC** [comment]
> One thing to add is that datetime conversion was not centralized in the 903 tool because some rules expect the dates as strings. For example rule [632 expects date values to have zz](https://github.com/data-to-insight/quality-lac-data-beta-validator/issues/274) in them as placeholders for unknown values. If datetime conversion is done centrally and before the validation process, all those dates will be marked as invalid.

I think rule 632 (and the new-for-2023/24 rules #672 and #673) are the only ones where the date needs to accommodate strings with zz substitution.  (Affecting the `<DATE_PERM>`, `<SW_DECOM>` and `<SW_DEC>` fields specifically).  All other dates should be correct.

Perhaps these three fields could be duplicated on the data frames at ingress (e.g. as `<DATE_PERM_STR>` or similar) before running a centralised datetime conversion on all of the original date fields?
