### ISSUE TITLE
Update default year in validator (FE and backend tests)

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/csc-validator-be-903#769]
Currently the tool, both in the FE application (`__main__.py` ?) and the backend tests (e.g. `test_get_year_ruleset()`), defaults to 2022/23 rules. This is probably overdue for updating to 2023/24.

**Comment by SLornieCYC** [comment]
Looking at the FE repository I assume it's this line that would need changing over there to set the dropdown default?

![image](https://github.com/data-to-insight/csc-validator-be-903/assets/89449804/7a857eb4-d332-4954-b8ef-9fe0658e1285)

https://github.com/data-to-insight/csc-validator-fe/blob/58e4a005cae002253b717db99750ba13fc7d20c3/src/pages/loadData/LoadData.tsx#L60C3-L60C72

**Comment by WillLP-code** [comment]
> Looking at the FE repository I assume it's this line that would need changing over there to set the dropdown default?
> 
> ![image](https://private-user-images.githubusercontent.com/89449804/325639644-7a857eb4-d332-4954-b8ef-9fe0658e1285.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTU1MjUsIm5iZiI6MTcxNDExNTIyNSwicGF0aCI6Ii84OTQ0OTgwNC8zMjU2Mzk2NDQtN2E4NTdlYjQtZDMzMi00OTU0LWI4ZWYtOWZlMDY1OGUxMjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA3MDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MjRlOGM3NGZkNWUyOTU3ZDYyOTVmOTNkNjY5OWIyY2Q4MGQ4OTcwZTBhNmY1ODRjMmViMzY1NWY3ODE5ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ga_NQRdqWtkWX7F62xj6J46If3svNpHuTkDu_848uCg)
> 
> https://github.com/data-to-insight/csc-validator-fe/blob/58e4a005cae002253b717db99750ba13fc7d20c3/src/pages/loadData/LoadData.tsx#L60C3-L60C72

I haven't used react before, which I think is the framework this is written in, so I'll have a bit of a dig and see what comes up, but I'm guessing you're right!

**Comment by SLornieCYC** [comment]
Re-opening this as a reminder to sort the FE default value too (and dropdown option for next year!).

**Comment by WillLP-code** [comment]
Judging my rpc_main, the API, this code gets the collection year:
`
@app.call
def get_rules(collection_year: str) -> str:
    """
    :param str ruleset: validation year e.g "2023" for 2022/2023 validation rules.
    :return rules_df: available rule codes and definitions according to chosen ruleset.
    """
    ruleset_registry = get_year_ruleset(collection_year)
`

So, having looked at the other file you linked, it looks like you're right for changing the default in the FE. I'm just trying to work out how I can change the list of available collection years in the 903 to include a 2022/23 as well!

**Comment by SLornieCYC** [comment]
I think the list of available years exists in the separate files for CIN and 903:

https://github.com/data-to-insight/csc-validator-fe/blob/58e4a005cae002253b717db99750ba13fc7d20c3/src/pages/loadData/LoadDataCIN.tsx#L203-L204

https://github.com/data-to-insight/csc-validator-fe/blob/58e4a005cae002253b717db99750ba13fc7d20c3/src/pages/loadData/LoadData903.tsx#L344-L345

**Comment by WillLP-code** [comment]
Closing this because of linked PR in FE repo:

[PR](https://github.com/data-to-insight/csc-validator-fe/pull/184)

**Comment by SLornieCYC** [comment]
> Closing this because of linked PR in FE repo:
> 
> [PR](https://github.com/data-to-insight/csc-validator-fe/pull/184)

I don't think the deployed 903 tool updated after that PR.  The CIN one has updated fine but I think somewhere the git action to daily-chain it through to the dummy 903 FE repo broke.

**Comment by WillLP-code** [comment]
> > Closing this because of linked PR in FE repo:
> > [PR](https://github.com/data-to-insight/csc-validator-fe/pull/184)
> 
> I don't think the deployed 903 tool updated after that PR. The CIN one has updated fine but I think somewhere the git action to daily-chain it through to the dummy 903 FE repo broke.

I noticed this, I was going to push the update on the back-end later (after the D2I open house) and if that doesn't sort it, I'll have another look!
