### ISSUE TITLE
Error code 197 - Reason for no Strengths and Difficulties (SDQ) score is not required if Strengths and Difficulties Questionnaire score is filled in.

### ISSUE THREAD

**Issue by mwaddoups** [data-to-insight/csc-validator-be-903#84]
#### Error code
197
#### Description to display
Reason for no Strengths and Difficulties (SDQ) score is not required if Strengths and Difficulties Questionnaire score is filled in.
#### DfE Long-form description of error
If a child has been looked after for 12 months continuously at 31 March of the current collection year and they were aged between 4 and 16 years old on the date of their last assessment, then the SDQ score should be completed.  If the child has an SDQ score, then the SDQ score field should be completed and the reason for no SDQ score field should be left blank.  If no SDQ score is available, then the SDQ score field should be left blank and the reason for no SDQ score field should be completed in the range SDQ1 to SDQ5.
#### DfE suggested coding
If `<SDQ_SCORE>` has been provided then `<SDQ_REASON>` should not be provided

For further info, refer to the DfE validation document [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/974999/Children_looked_after_data_collection_2020_to_2021_validation_checks_-_version_1.3.pdf)

**Comment by SLornieCYC** [comment]
Rule renamed 197**a** in the 2021 v1.2 validation rules: [Children looked after return 2021 to 2022: technical specifications](https://www.gov.uk/government/publications/children-looked-after-return-2021-to-2022-technical-specifications)
